# Generated by Django 5.0.9 on 2024-12-01 16:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import views.userAuth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivateReason',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='CodigoDesativacao')),
                ('choice_reason', models.CharField(choices=[('NG', 'Não gostei do Sistema'), ('MG', 'Estou mudando de sistema'), ('ER', 'Muitos erros'), ('OU', 'Outros motivos...')], max_length=2, verbose_name='Campo de Escolha')),
                ('reason', models.TextField(blank=True, max_length=255, null=True, verbose_name='Motivo da desativação do Usuário')),
            ],
            options={
                'db_table': 'Desativacao',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('imagem', models.ImageField(default='userDefault/user.png', upload_to=views.userAuth.models.user_image_upload_path)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Interno')),
                ('usuario', models.CharField(max_length=150, unique=True, verbose_name='Nome de Usuário')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=11, null=True, verbose_name='Telefone')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.endereco', verbose_name='Endereço')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Desativacao',
            fields=[
                ('data', models.DateField(auto_created=True, auto_now=True, verbose_name='Data Realizada')),
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='CodigoUsuarioDesativacao')),
                ('codigodesativacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.deactivatereason', verbose_name='CodigoDesativacao')),
                ('codigousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CodigoUsuario')),
            ],
            options={
                'db_table': 'Usuario_Desativacao',
            },
        ),
    ]
