# Generated by Django 5.0.9 on 2024-12-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_motorista',
            field=models.BooleanField(default=False, verbose_name='Motorista?'),
        ),
    ]
